name: Build and Attach Binaries to Release

on:
  release:
    types:
      - released # Trigger when a release is published

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Cross (if needed)
        run: cargo install cross --locked

      - name: Build Binary
        run: |
          if [[ "${{ matrix.platform }}" == *"apple-darwin"* ]]; then
            rustup target add ${{ matrix.platform }}
            cargo build --release --target ${{ matrix.platform }}
          else
            cross build --release --target ${{ matrix.platform }}
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/${{ matrix.platform }}/release/your_binary_name dist/your_binary_name-${{ matrix.platform }}
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.platform }}
          path: dist/

  attach:
    name: Attach Binaries to Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist/

      - name: Attach files to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          files: dist/*
